remote_theme: pmarsceill/just-the-docs
heading_anchors: true
search_enabled: true
logo: "https://explosion.ai/blog/img/introducing-spacy.jpg"
color_scheme: "dark"
aux_links:
  "Workshop Notebooks":
    - "https://spacy.apjan.co:8000"
